---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.2
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./src/administrator/components/com_jed/vendor/bin/php-cs-fixer fix -vvv --dry-run --diff
      - ./src/administrator/components/com_jed/vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .
      - echo $(date)

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 18e4d251a49437161fd2391a9de521a4479ff62d39baacc76a5ebb17a9b592a1

...
